version: '3'

volumes:
  plex-data:
    driver: local
    driver_opts:
      type: none
      device: d:/media
      o: bind
  download-data:
    driver: local
    driver_opts:
      type: none
      device: d:/media/downloads
      o: bind
  shows-data:
    driver: local
    driver_opts:
      type: none
      device: d:/media/shows
      o: bind
  movies-data:
    driver: local
    driver_opts:
      type: none
      device: d:/media/movies
      o: bind


networks:
  home_server:
    name: homeserver
    driver: bridge

services:

  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Optional, only if you want docker integration
      - ./config/docker/homarr/configs:/app/data/configs
      - ./config/docker/homarr/icons:/app/public/icons
      - ./config/docker/homarr/data:/data
    ports:
      - 7575:7575
    networks:
      - home_server

  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    environment:
        PGID: '1000'
        PUID: '1024'
        VERSION: docker
    volumes:
      - ./config/docker/plex/config:/config
      - plex-data:/media
    ports:
      - 32400:32400 # Plex
    restart: unless-stopped
    networks:
      - home_server

  portainer:
    image: portainer/portainer-ce:alpine
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: always
    ports:
      - 9000:9000
    networks:
      - home_server

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - ./config/docker/sonarr/data:/config
      - download-data:/downloads
      - shows-data:/shows
    restart: unless-stopped
    ports:
      - 8989:8989
    networks:
      - home_server

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - ./config/docker/radarr/data:/config
      - download-data:/downloads
      - movies-data:/movies
    restart: unless-stopped
    ports:
      - 7878:7878 # radarr
    networks:
      - home_server

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - ./config/docker/prowlarr/data:/config
    restart: unless-stopped
    ports:
      - 9696:9696
    networks:
      - home_server

  qbittorrent:
    image: linuxserver/qbittorrent:version-4.6.0-r0
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - UMASK=022
      - WEBUI_PORT=8090
    volumes:
      - ./config/docker/provision/qbittorrent:/config
      - download-data:/downloads
    restart: unless-stopped
    ports:
      - 8090:8090
    networks:
      - home_server

  requestrr:
    image: thomst08/requestrr:latest
    container_name: requestrr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./config/docker/requestrr/config:/root/config
    ports:
      - 4545:4545
    restart: unless-stopped
    networks:
      - home_server

  proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: proxy
    restart: unless-stopped
    environment:
     - PUID=1000
     - PGID=1000
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./config/docker/proxy/data:/data
      - ./config/docker/proxy/letsencrypt:/etc/letsencrypt
    networks:
      - home_server