name: homelab

services:
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:0.15.10
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${CONFIG_FOLDER}/homarr/configs:/app/data/configs
      - ${CONFIG_FOLDER}/homarr/icons:/app/public/icons
      - ${CONFIG_FOLDER}/homarr/data:/data
    ports:
      - 7575:7575

  plex:
    image: lscr.io/linuxserver/plex:1.41.7
    container_name: plex
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - VERSION=${VERSION}
    volumes:
      - ${CONFIG_FOLDER}/plex/config:/config
      - ${MEDIA_FOLDER}:/media
    ports:
      - 32400:32400
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:4.0.14
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_FOLDER}/sonarr/data:/config
      - ${MEDIA_FOLDER}/downloads:/downloads
      - ${MEDIA_FOLDER}/shows:/shows
    restart: unless-stopped
    ports:
      - 8989:8989

  radarr:
    image: lscr.io/linuxserver/radarr:5.26.1-nightly
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_FOLDER}/radarr/data:/config
      - ${MEDIA_FOLDER}/downloads:/downloads
      - ${MEDIA_FOLDER}/movies:/movies
    restart: unless-stopped
    ports:
      - 7878:7878

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:1.36.3
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_FOLDER}/prowlarr/data:/config
    restart: unless-stopped
    ports:
      - 9696:9696

  qbittorrent:
    image: linuxserver/qbittorrent:5.1.0
    container_name: qbittorrent
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=022
      - WEBUI_PORT=8090
    volumes:
      - ${CONFIG_FOLDER}/provision/qbittorrent:/config
      - ${MEDIA_FOLDER}/downloads:/downloads
    restart: unless-stopped
    ports:
      - 8090:8090

  overseerr:
    image: sctx/overseerr:1.34.0
    container_name: overseerr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - PORT=5055
    ports:
      - 5055:5055
    volumes:
      - ${CONFIG_FOLDER}/overseerr:/app/config
    restart: unless-stopped

  requestrr:
    image: thomst08/requestrr:v2.1.7
    container_name: requestrr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_FOLDER}/requestrr/config:/root/config
    ports:
      - 4545:4545
    restart: unless-stopped

  npm:
    image: jc21/nginx-proxy-manager:2.12.3
    container_name: npm
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - 80:80
      - 81:81
      - 443:443
    volumes:
      - ${CONFIG_FOLDER}/proxy/data:/data
      - ${CONFIG_FOLDER}/proxy/letsencrypt:/etc/letsencrypt

networks:
  default:
    name: homeserver
    driver: bridge